### ISSUE TITLE
Getting Invalid header token sometimes when doing cursor.each

### ISSUE THREAD

**Issue by couds** [arangodb/arangojs#651]
Hi. I'm having an issue with the arangojs driver (but seem that the real issue is on the server idk),
I'm importing > 200.000 documents and after that I run this
```
const citiesCursor = await db.query(
    aql`FOR doc IN locations
    FILTER doc.type == "city" and doc.country 
    INSERT { _from: doc.country, _to: doc._id } IN geography
    REPLACE doc WITH UNSET(doc, "country") in locations
    return doc`,
  );
  await citiesCursor.each(city => {
    cities[city.booking.id] = city;
  });
```

The query ran fine (took one-two minutes) but when Iterating the cursor I got an error `HPE_INVALID_HEADER_TOKEN` , and inspecting the request/response made by the driver there seem to be an invalid header on the response
```
[PUT] /_api/cursor/2199034615410
HTTP/1.1 200 OK <------
Date: Wed, 04 Mar 2020 09:33:30 GMT
Content-Type: application/json
Content-Length: 306384
Vary: Accept-Encoding
Strict-Transport-Security: max-age=15724800; includeSubDomains
X-Content-Type-Options: nosniff
X-Arango-Request-Forwarded-To: CRDN-n5snxnie
Http/1.1: OK <------------------ THIS ONE IS INVALID?
Connection: keep-alive
```
I use Arango Operator in cluster mode with 3 coordinators and 3 db servers

```
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "arango"
  namespace: arangodb
spec:
  mode: Cluster
  image: arangodb/arangodb:3.6.1
  environment: Production
  externalAccess:
    type: None
  tls:
    caSecretName: None
  dbservers:
    resources:
      requests:
        cpu: 500m
        memory: 100Mi
      limits:
        cpu: 3000m
        memory: 6Gi
  coordinators:
    resources:
      requests:
        cpu: 500m
        memory: 100Mi
      limits:
        cpu: 3000m
        memory: 6Gi
```

I'm using the Docker image `node:12-alpine` (this also happen with node 10)
